### ISSUE TITLE
Export the whole template object?

### ISSUE THREAD

**Issue by callumlocke** [unfold/browserify-hogan#5]
@sbrekken  do you mind if I make the following change to this transform: I want to change it so the compiled module exports the whole Hogan template object, not just the render function. So usage would change to:

``` javascript
var myTemplate = require('./my-template.mustache');
$('body').append( myTemplate.render({foo: 'bar'} );
                             ^^^^^^
```

reasons:
- it's more in line with Hogan's docs (they describe a "compiled template" as being an object with a `render` method, not just a function)
- it would make it easier to inspect compiled template code (for debugging purposes)... Currently if you console.log the template, you just get `function (data) {return template.render(data)}`, so you have to go looking in the bundled code.

I just wanted to check if you had any objection before I go ahead and do this, as it's effectively an API change (so I would bump the version to 0.1.0).

**Comment by simenbrekken** [comment]
Good idea, go ahead!
